language: node_js
node_js:
- '12'
sudo: true
addons:
  chrome: stable
script:
- cd ./seedling-angular
- npm install
- npm run prod
before_install:
- openssl aes-256-cbc -K $encrypted_92725ca94bf5_key -iv $encrypted_92725ca94bf5_iv
  -in deploy-key.enc -out deploy-key -d
