language: node_js
node_js:
- '12'
sudo: true
addons:
  ssh_known_hosts:
  - 178.128.99.175
script:
- cd ./seedling-angular
# - npm install
# - npm run prod
env:
  global:
  - REMOTEAPPDIR=/home/travisci
  - REMOTEUSER=travisci
  - REMOTEHOST=178.128.99.175
after_success:
# - cd ./
# - chmod 600 deploy-key && mv deploy-key ~/.ssh/id_rsa
- pwd
- ls
- eval "$(ssh-agent -s)"
- cat deploy-key
- chmod 600 deploy-key
- echo -e "Host 178.128.99.175\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add deploy_key
- echo "deploy to 178.128.99.175"
- cd ./seedling-angular
- tar cvfz src.tar.gz src/
- scp src.tar.gz travisci@178.128.99.175:~/
before_install:
- openssl aes-256-cbc -K $encrypted_92725ca94bf5_key -iv $encrypted_92725ca94bf5_iv
  -in deploy-key.enc -out deploy-key -d
