matrix:
  include:
    - language: java
      sudo: required

      services:
        - docker


      before_install:
        - cd ./seedling-spring
        - tar -cJf src.tar.xz src
        - docker build -t seedling/spring -f Dockerfile.dev .
    
    - language: node.js
      node_js: 
        - "12.0"
      sudo: required  

      before_script:
        - cd ./seedling-angular
        - npm install
        - npm run build
      



deploy:
  addons:
    ssh_known_hosts:
    - 178.128.99.175

  env:
    global:
    - REMOTEAPPDIR=/home/travisci
    - REMOTEUSER=travisci
    - REMOTEHOST=178.128.99.175
  
  script:  
    - cd ..
    - pwd
    - cat deploy-key
    - chmod 600 deploy-key && mv deploy-key ~/.ssh/id_rsa
    - echo "deploy to 178.128.99.175"

    - cd ./seedling-angular
    - tar cvfz dist.tar.gz dist/
    - scp src.tar.gz travisci@178.128.99.175:~/

before_install:
- openssl aes-256-cbc -K $encrypted_92725ca94bf5_key -iv $encrypted_92725ca94bf5_iv
  -in deploy-key.enc -out deploy-key -d


